// Every bag from the "محاصيل" highlight on @subcoffee1, read off the labels.
// img: file in public/images/crops-web (plus a "-sm" thumbnail).
// tone: the bag's signature colour — drives the stage background on the crops page.
// alt: altitude in metres, as printed. Missing fields were not on the label.

export const roasters = {
  blackknight: { ar: 'بلاك نايت', en: 'Black Knight' },
  shovel: { ar: 'شوفل', en: 'Shovel' },
  tooz: { ar: 'توز', en: 'Tooz' },
  olala: { ar: 'أولالا', en: 'Olala' },
  roastinghouse: { ar: 'بيت التحميص', en: 'Roasting House' },
  graph: { ar: 'جراف', en: 'Graph' },
  w: { ar: 'دبليو', en: 'W' },
  threebean: { ar: 'ثري بين', en: '3Bean' },
  woods: { ar: 'وودز', en: 'Woods' },
  duha: { ar: 'ضحى', en: 'Duha' },
  sout: { ar: 'صوت', en: 'Sout' },
  slope: { ar: 'سلوب', en: 'Slope' },
  twelvecups: { ar: 'تويلف كبس', en: 'Twelve Cups' },
  suwaa: { ar: 'صُواع', en: 'Suwaa' },
};

export const origins = {
  ethiopia: { ar: 'إثيوبيا', en: 'Ethiopia' },
  colombia: { ar: 'كولومبيا', en: 'Colombia' },
  brazil: { ar: 'البرازيل', en: 'Brazil' },
  elsalvador: { ar: 'السلفادور', en: 'El Salvador' },
  yemen: { ar: 'اليمن', en: 'Yemen' },
  uganda: { ar: 'أوغندا', en: 'Uganda' },
  costarica: { ar: 'كوستاريكا', en: 'Costa Rica' },
  blend: { ar: 'مزيج', en: 'Blend' },
};

export const processes = {
  washed: { ar: 'مغسولة', en: 'Washed' },
  natural: { ar: 'مجففة', en: 'Natural' },
  honey: { ar: 'عسلية', en: 'Honey' },
  anaerobic: { ar: 'مجففة لاهوائية', en: 'Natural Anaerobic' },
  special: { ar: 'معالجة خاصة', en: 'Special Process' },
};

const p = (
  img,
  roaster,
  origin,
  process,
  ar,
  en,
  notesAr,
  notesEn,
  tone,
  extra = {},
) => ({
  img,
  roaster,
  origin,
  process,
  ar,
  en,
  notesAr,
  notesEn,
  tone,
  ...extra,
});

// prettier-ignore
export const crops = [
  p('02', 'blackknight', 'colombia', 'washed', 'اكسيلسو', 'Excelso',
    ['كراميل', 'سكر بني', 'لوز', 'حمضية ناعمة'],
    ['Caramel', 'Brown sugar', 'Almond', 'Soft citrus'],
    '#9c1c2b', { alt: '1700', variety: 'Caturra', weight: '1000g' }),
  p('03', 'blackknight', 'brazil', 'natural', 'ريو', 'Rio',
    ['كراميل', 'شوكولاتة', 'مكسرات'],
    ['Caramel', 'Chocolate', 'Nuts'],
    '#1d8a5f', { alt: '1200', variety: 'Catuai', weight: '1000g' }),
  p('04', 'blackknight', 'ethiopia', 'natural', 'قوجي', 'Guji',
    ['توت أحمر', 'فراولة', 'عنب', 'شوكولاتة'],
    ['Red berry', 'Strawberry', 'Grape', 'Chocolate'],
    '#1d3fa0', { alt: '2180', variety: 'Heirloom', weight: '1000g' }),
  p('05', 'blackknight', 'elsalvador', 'honey', 'سيلفر', 'Silver',
    ['توت', 'كراميل', 'لوز', 'شوكولاتة داكنة'],
    ['Berries', 'Caramel', 'Almonds', 'Dark chocolate'],
    '#2152c4', { alt: '1600', weight: '1000g' }),
  p('06', 'shovel', 'yemen', 'anaerobic', 'اليمن', 'Yemen',
    ['توت', 'عنب', 'زبيب'],
    ['Berries', 'Grape', 'Raisins'],
    '#e89a12', { weight: '250g' }),
  p('07', 'shovel', 'blend', null, 'فروتي', 'Frutti',
    ['فاكهية', 'توت', 'شوكولاتة'],
    ['Fruity', 'Berry', 'Chocolate'],
    '#f0a91c', { weight: '250g' }),
  p('08', 'tooz', 'uganda', 'natural', 'كينزا', 'Kinza',
    ['تفاح', 'عنب أحمر', 'برقوق'],
    ['Apple', 'Red grapes', 'Plum'],
    '#b81d3a', { variety: 'SL14, SL28' }),
  p('09', 'tooz', 'colombia', 'washed', 'هويلا', 'Huila',
    ['سكر بني', 'فواكه استوائية', 'ياسمين'],
    ['Brown sugar', 'Tropical fruit', 'Jasmine'],
    '#a8182f', { variety: 'Castillo' }),
  p('10', 'tooz', 'ethiopia', 'natural', 'شلشلي', 'Chelchele',
    ['شوكولاتة', 'حمضيات', 'زهور', 'توت'],
    ['Chocolate', 'Citrus', 'Flowers', 'Berries'],
    '#c02440', { variety: 'Heirloom' }),
  p('11', 'olala', 'elsalvador', 'washed', 'فيستا', 'Vista',
    ['شوكولاتة داكنة', 'كراميل', 'سكر بني'],
    ['Dark chocolate', 'Caramel', 'Brown sugar'],
    '#3b57d0', { alt: '1500', variety: 'Bourbon' }),
  p('12', 'olala', 'colombia', 'washed', 'اكسيلسو', 'Excelso',
    ['كركديه', 'شاي فواكه', 'تفاح'],
    ['Hibiscus', 'Fruit tea', 'Apple'],
    '#d84b8f', { alt: '2000', variety: 'Caturra' }),
  p('13', 'roastinghouse', 'ethiopia', 'honey', 'أومني', 'Omni',
    ['زهور', 'حلاوة بالقشطة', 'بسكويت'],
    ['Floral', 'Cream fudge', 'Biscuits'],
    '#a4502f', { alt: '1950–2300', variety: 'Heirloom', weight: '227g' }),
  p('14', 'roastinghouse', 'costarica', 'washed', 'سانتا ماريا', 'Santa Maria',
    ['زهور', 'مكسرات محمصة', 'شوكولاتة بيضاء'],
    ['Flowers', 'Roasted nuts', 'White chocolate'],
    '#3f7a4c', { alt: '1900', variety: 'Catuai, Caturra', weight: '227g' }),
  p('15', 'graph', 'yemen', 'natural', 'حراز', 'Haraz',
    ['فانيلا', 'توت', 'شوكولاتة'],
    ['Vanilla', 'Berries', 'Chocolate'],
    '#34303d', { alt: '1900–2500', variety: 'Typica', weight: '250g' }),
  p('16', 'graph', 'blend', null, 'كورال', 'Coral',
    ['شوكولاتة', 'كراميل', 'بندق'],
    ['Chocolate', 'Caramel', 'Hazelnut'],
    '#8f1e24', { weight: '250g' }),
  p('17', 'w', 'ethiopia', 'natural', 'يرغاتشيف', 'Yirgacheffe',
    ['عنب', 'فراولة'],
    ['Grape', 'Strawberry'],
    '#1f6b43', { alt: '2100' }),
  p('18', 'w', 'ethiopia', 'natural', 'قوجي', 'Guji',
    ['توت أحمر', 'عنب'],
    ['Red berry', 'Grape'],
    '#236f49', { alt: '2100' }),
  p('19', 'threebean', 'ethiopia', 'natural', 'قوجي', 'Guji',
    ['حلاوة', 'كراميل', 'فواكه', 'ياسمين'],
    ['Sweet', 'Caramel', 'Fruit', 'Jasmine'],
    '#1c2c50', { alt: '2100–2300', weight: '1kg' }),
  p('20', 'threebean', 'colombia', 'washed', 'ريو ماندلينا', 'Rio Mandalina',
    ['شوكولاتة داكنة', 'سكر بني'],
    ['Dark chocolate', 'Brown sugar'],
    '#22335a', { weight: '1kg' }),
  p('21', 'woods', 'brazil', null, 'ستامايا', 'Stamaya',
    ['عنب أخضر', 'شوكولاتة داكنة', 'قوام كريمي', 'حمضية الأناناس'],
    ['Green grape', 'Dark chocolate', 'Creamy body', 'Pineapple acidity'],
    '#c44a22', { weight: '250g' }),
  p('22', 'woods', 'colombia', 'special', 'زارزا', 'Zarza',
    ['شوكولاتة', 'لوز', 'توت أسود'],
    ['Chocolate', 'Almond', 'Blackberry'],
    '#b8421f', { variety: 'Mixed varieties', weight: '250g' }),
  p('23', 'duha', 'ethiopia', 'washed', 'شلبيسا', 'Chelbesa',
    ['خوخ', 'لافندر', 'عنب'],
    ['Peach', 'Lavender', 'Grape'],
    '#17635e', { weight: '250g' }),
  p('24', 'duha', 'ethiopia', 'natural', 'قوجي', 'Guji',
    ['توت أحمر', 'فانيلا', 'كراميل'],
    ['Red berry', 'Vanilla', 'Caramel'],
    '#146059', { weight: '250g' }),
  p('25', 'sout', 'ethiopia', 'natural', 'سيدامو', 'Sedamo',
    ['شوكولاتة داكنة', 'كيوي', 'جريب فروت'],
    ['Dark chocolate', 'Kiwi', 'Grapefruit'],
    '#2c31a3', { alt: '1900', weight: '250g' }),
  p('26', 'sout', 'uganda', 'natural', 'كاسينجا', 'Kasinga',
    ['شوكولاتة داكنة', 'برقوق', 'قصب السكر', 'كراميل'],
    ['Dark chocolate', 'Plum', 'Sugar cane', 'Caramel'],
    '#2a2a33', { alt: '2200', weight: '250g' }),
  p('27', 'slope', 'colombia', 'washed', 'أروكا', 'Arauca',
    ['شوكولاتة داكنة', 'كراميل', 'قوام ممتلئ'],
    ['Dark chocolate', 'Caramel', 'Full body'],
    '#b8935a', { alt: '1700', variety: 'Caturra, Castillo', weight: '1kg' }),
  p('28', 'twelvecups', 'ethiopia', 'natural', 'هامبيلا', 'Hambela',
    ['توت أزرق', 'توت العليق', 'أناناس'],
    ['Blueberry', 'Raspberry', 'Pineapple'],
    '#d8671c', { alt: '1900–2200', variety: 'Heirloom' }),
  p('29', 'suwaa', 'elsalvador', 'washed', 'ديفيسادِرو', 'Divisadero',
    ['مكسرات', 'كراميل', 'شوكولاتة بالحليب'],
    ['Nuts', 'Caramel', 'Milk chocolate'],
    '#24348f', { weight: '1kg' }),
  p('30', 'suwaa', 'colombia', 'natural', 'أنسيرما', 'Anserma',
    ['سكر بني', 'توت بري', 'شمام', 'خوخ'],
    ['Brown sugar', 'Cranberry', 'Cantaloupe', 'Peach'],
    '#c9a227', { weight: '1kg' }),
  p('31', 'suwaa', 'ethiopia', 'natural', 'هامبيلا بوكو', 'Hambela Buku',
    ['خوخ', 'فراولة', 'شوكولاتة'],
    ['Peach', 'Strawberry', 'Chocolate'],
    '#8e3a3f', { weight: '1kg' }),
];

// Instagram DM — the shop has no online checkout, orders go through the account.
export const ORDER_URL = 'https://ig.me/m/subcoffee1';
